name: Deploy
on:
  push: 
    branches: develop

  pull_request:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Test step
        run: "deno task test"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "hn-telegram-bot"
          entrypoint: "src/bot.ts"
          root: "."
